# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the centroid of polygons, ncol of \code{poly} must be equal or larger than 3.
#' @param poly, polygon consist of \code{points} Index 
#' @param points, M x 2 matrix, (x,y) of points.
#' @return coordinates of the centroids of \code{poly}
getCentroid <- function(poly, points) {
    .Call(`_PIHMgisR_getCentroid`, poly, points)
}

#' Calculate the Polygon Area;
#' @param X required
#' @param Y required
#' @return Area
polygonArea <- function(X, Y) {
    .Call(`_PIHMgisR_polygonArea`, X, Y)
}

#' Identify whether every row of \code{m} is same as \code{v};
#' @param x required
#' @param m required
#' @return TRUE/FALSE of matching
rowMatch <- function(x, m) {
    .Call(`_PIHMgisR_rowMatch`, x, m)
}

#' Determine the topological relation among triangles. 
#' @param tri triangle defination, m x 3
#' @return topological relation of triangles. m x 4; cols = c(ID, Nabor1, Nabor2, Nabor3)
triTopology <- function(tri) {
    .Call(`_PIHMgisR_triTopology`, tri)
}

