# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_PIHMgisR_rcpp_hello_world`)
}

#' Identify whether every row of \code{m} is same as \code{v};
#' @param x required
#' @param m required
#' @return TRUE/FALSE of matching
rowMatch <- function(x, m) {
    .Call(`_PIHMgisR_rowMatch`, x, m)
}

